export const APP_CONFIG = {
  APP_NAME: "Products",
  VERSION: "1.0.0",
  DESCRIPTION: "Product Management Dashboard",
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 5,
} as const;

export const VALIDATION_LIMITS = {
  MAX_PRODUCT_NAME_LENGTH: 100,
  MAX_CATEGORY_LENGTH: 50,
  MIN_PRICE: 0.01,
  MAX_PRICE: 999999.99,
  MAX_STOCK: 999999,
  MIN_STOCK: 0,
} as const;

export const UI_CONSTANTS = {
  DEBOUNCE_DELAY: 300,
  ANIMATION_DURATION: 200,
  TOAST_DURATION: 5000,
  LOADING_DELAY: 500,
} as const;

export const STOCK_THRESHOLDS = {
  LOW_STOCK: 10,
  CRITICAL_STOCK: 5,
  OUT_OF_STOCK: 0,
} as const;

export const PRODUCT_STATUS = {
  ACTIVE: "active",
  ARCHIVED: "archived",
} as const;

export const SORT_DIRECTIONS = {
  ASC: "asc",
  DESC: "desc",
} as const;

export const constants = {
  APP_NAME: APP_CONFIG.APP_NAME,
  VERSION: APP_CONFIG.VERSION,
  DEFAULT_PAGE_SIZE: PAGINATION.DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE: PAGINATION.MAX_PAGE_SIZE,
  MAX_PRODUCT_NAME_LENGTH: VALIDATION_LIMITS.MAX_PRODUCT_NAME_LENGTH,
  MAX_CATEGORY_LENGTH: VALIDATION_LIMITS.MAX_CATEGORY_LENGTH,
  MIN_PRICE: VALIDATION_LIMITS.MIN_PRICE,
  MAX_PRICE: VALIDATION_LIMITS.MAX_PRICE,
  MAX_STOCK: VALIDATION_LIMITS.MAX_STOCK,
  DEBOUNCE_DELAY: UI_CONSTANTS.DEBOUNCE_DELAY,
  ANIMATION_DURATION: UI_CONSTANTS.ANIMATION_DURATION,
  TOAST_DURATION: UI_CONSTANTS.TOAST_DURATION,
  LOW_STOCK_THRESHOLD: STOCK_THRESHOLDS.LOW_STOCK,
  CRITICAL_STOCK_THRESHOLD: STOCK_THRESHOLDS.CRITICAL_STOCK,
};
